[project]
name = "packing-mcp"
version = "1.0.0"
description = "MCP server for generating packing lists for various activities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.1",
]