"""
Tourist attractions MCP configuration mocks data.
"""

# World Tourist Attractions API configuration
ATTRACTIONS_BASE_URL = "https://www.world-tourist-attractions-api.com"
API_VERSION = "v1"

# API Endpoints
ENDPOINTS = {
    "attraction_by_id": f"/api/{API_VERSION}/attraction",
    "random_famous": f"/api/{API_VERSION}/random/famous",
    "random_india": f"/api/{API_VERSION}/random/india", 
    "wonders": f"/api/{API_VERSION}/wonders",
    "search": f"/api/{API_VERSION}/search",
    "categories": f"/api/{API_VERSION}/categories"
}

# Attraction categories
ATTRACTION_CATEGORIES = {
    "historical": "Historical Sites",
    "natural": "Natural Wonders", 
    "cultural": "Cultural Sites",
    "religious": "Religious Sites",
    "modern": "Modern Attractions",
    "museums": "Museums",
    "parks": "Parks & Gardens",
    "beaches": "Beaches",
    "mountains": "Mountains",
    "architecture": "Architecture",
    "entertainment": "Entertainment",
    "adventure": "Adventure Sports"
}

# Popular countries/regions
POPULAR_REGIONS = [
    "India", "France", "Italy", "Spain", "Greece", "Egypt", 
    "Thailand", "Japan", "China", "USA", "UK", "Germany",
    "Turkey", "Morocco", "Brazil", "Peru", "Australia"
]

# Booking status codes
BOOKING_STATUS = {
    "pending": "Pending Confirmation",
    "confirmed": "Confirmed", 
    "cancelled": "Cancelled",
    "completed": "Completed"
}

# Default values
DEFAULT_SEARCH_LIMIT = 20
MAX_SEARCH_LIMIT = 100
DEFAULT_RATING_MIN = 3.0

# Mock attractions data for demonstration
MOCK_ATTRACTIONS = [
    {
        "id": 1,
        "name": "Eiffel Tower",
        "description": "Iconic iron lattice tower located on the Champ de Mars in Paris, France",
        "category": "architecture",
        "location": {"city": "Paris", "country": "France", "region": "Île-de-France", "continent": "Europe"},
        "rating": 4.6,
        "image_url": "https://example.com/eiffel-tower.jpg",
        "website": "https://www.toureiffel.paris",
        "opening_hours": "9:30 AM - 11:45 PM",
        "entry_fee": "€29.40 - €73.30",
        "disability_accessible": True,
        "outdoors": False,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Romantic",
        "recommended_packing_list": ["Camera", "Water bottle", "Sunscreen"]
    },
    {
        "id": 2,
        "name": "Taj Mahal",
        "description": "Ivory-white marble mausoleum on the right bank of the river Yamuna in Agra",
        "category": "historical",
        "location": {"city": "Agra", "country": "India", "region": "Uttar Pradesh", "continent": "Asia"},
        "rating": 4.8,
        "image_url": "https://example.com/taj-mahal.jpg",
        "website": "https://www.tajmahal.gov.in",
        "opening_hours": "6:00 AM - 7:00 PM",
        "entry_fee": "₹1100 (foreigners), ₹50 (Indians)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-100",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Low",
        "time_needed": "2-4 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Hat", "Camera", "Comfortable shoes"]
    },
    {
        "id": 3,
        "name": "Colosseum",
        "description": "Ancient Roman amphitheater in the center of Rome, Italy",
        "category": "historical",
        "location": {"city": "Rome", "country": "Italy", "region": "Lazio", "continent": "Europe"},
        "rating": 4.5,
        "image_url": "https://example.com/colosseum.jpg",
        "website": "https://www.coopculture.it",
        "opening_hours": "8:30 AM - 7:15 PM",
        "entry_fee": "€16 - €22",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "6+",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "1-2 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Water bottle", "Hat", "Guidebook"]
    },
    {
        "id": 4,
        "name": "Machu Picchu",
        "description": "Ancient Incan city set high in the Andes Mountains of Peru",
        "category": "historical",
        "location": {"city": "Cusco", "country": "Peru", "region": "Cusco", "continent": "South America"},
        "rating": 4.9,
        "image_url": "https://example.com/machu-picchu.jpg",
        "website": "https://www.machupicchu.gob.pe",
        "opening_hours": "6:00 AM - 5:30 PM",
        "entry_fee": "$47 - $62",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-20",
        "age_recommendation": "10+",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "4-6 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Hiking boots", "Raincoat", "Snacks", "Camera"]
    },
    {
        "id": 5,
        "name": "Louvre Museum",
        "description": "World's largest art museum and historic monument in Paris",
        "category": "museums",
        "location": {"city": "Paris", "country": "France", "region": "Île-de-France", "continent": "Europe"},
        "rating": 4.4,
        "image_url": "https://example.com/louvre.jpg",
        "website": "https://www.louvre.fr",
        "opening_hours": "9:00 AM - 6:00 PM",
        "entry_fee": "€17",
        "disability_accessible": True,
        "outdoors": False,
        "group_size": "1-40",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "3-4 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Camera", "Guidebook"]
    },
    {
        "id": 6,
        "name": "Great Wall of China",
        "description": "Ancient fortification built across northern China",
        "category": "historical",
        "location": {"city": "Beijing", "country": "China", "region": "Beijing", "continent": "Asia"},
        "rating": 4.7,
        "image_url": "https://example.com/great-wall.jpg",
        "website": "https://www.mutianyu.com",
        "opening_hours": "7:30 AM - 5:30 PM",
        "entry_fee": "¥45 - ¥65",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-50",
        "age_recommendation": "8+",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "3-5 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Hiking shoes", "Hat", "Water bottle"]
    },
    {
        "id": 7,
        "name": "Santorini",
        "description": "Beautiful Greek island with white buildings and blue domes",
        "category": "natural",
        "location": {"city": "Santorini", "country": "Greece", "region": "Cyclades", "continent": "Europe"},
        "rating": 4.6,
        "image_url": "https://example.com/santorini.jpg",
        "website": "https://www.santorini.com",
        "opening_hours": "24/7",
        "entry_fee": "Free",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-20",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "Full day",
        "pet_friendly": True,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Relaxing",
        "recommended_packing_list": ["Sunscreen", "Swimsuit", "Camera"]
    },
    {
        "id": 8,
        "name": "Angkor Wat",
        "description": "Largest religious monument in the world, originally a Hindu temple",
        "category": "religious",
        "location": {"city": "Siem Reap", "country": "Cambodia", "region": "Siem Reap", "continent": "Asia"},
        "rating": 4.8,
        "image_url": "https://example.com/angkor-wat.jpg",
        "website": "https://www.angkorwat.com",
        "opening_hours": "5:00 AM - 6:00 PM",
        "entry_fee": "$37 (1 day), $62 (3 days)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Spiritual",
        "recommended_packing_list": ["Hat", "Water bottle", "Camera"]
    },
    {
        "id": 9,
        "name": "Central Park",
        "description": "Large public park in Manhattan, New York City",
        "category": "parks",
        "location": {"city": "New York", "country": "USA", "region": "New York", "continent": "North America"},
        "rating": 4.3,
        "image_url": "https://example.com/central-park.jpg",
        "website": "https://www.centralparknyc.org",
        "opening_hours": "6:00 AM - 1:00 AM",
        "entry_fee": "Free",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-100+",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Free",
        "time_needed": "1-4 hours",
        "pet_friendly": True,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Relaxing",
        "recommended_packing_list": ["Picnic blanket", "Snacks", "Camera"]
    },
    {
        "id": 10,
        "name": "Petra",
        "description": "Archaeological city famous for rock-cut architecture and water conduit system",
        "category": "historical",
        "location": {"city": "Ma'an", "country": "Jordan", "region": "Ma'an", "continent": "Asia"},
        "rating": 4.7,
        "image_url": "https://example.com/petra.jpg",
        "website": "https://www.visitpetra.jo",
        "opening_hours": "6:00 AM - 6:00 PM",
        "entry_fee": "70 JOD (1 day), 55 JOD (2 days)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-20",
        "age_recommendation": "8+",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "3-5 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Hat", "Water bottle", "Camera"]
    },
    {
        "id": 11,
        "name": "Statue of Liberty",
        "description": "Neoclassical sculpture on Liberty Island in New York Harbor",
        "category": "modern",
        "location": {"city": "New York", "country": "USA", "region": "New York", "continent": "North America"},
        "rating": 4.4,
        "image_url": "https://example.com/statue-liberty.jpg",
        "website": "https://www.nps.gov/stli",
        "opening_hours": "8:30 AM - 4:00 PM",
        "entry_fee": "$23.80 - $24.30",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Patriotic",
        "recommended_packing_list": ["Camera", "Water bottle"]
    },
    {
        "id": 12,
        "name": "Sagrada Familia",
        "description": "Unfinished Roman Catholic minor basilica in Barcelona, Spain",
        "category": "religious",
        "location": {"city": "Barcelona", "country": "Spain", "region": "Catalonia", "continent": "Europe"},
        "rating": 4.6,
        "image_url": "https://example.com/sagrada-familia.jpg",
        "website": "https://sagradafamilia.org",
        "opening_hours": "9:00 AM - 8:00 PM",
        "entry_fee": "€26 - €40",
        "disability_accessible": True,
        "outdoors": False,
        "group_size": "1-30",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Spiritual",
        "recommended_packing_list": ["Camera", "Guidebook"]
    },
    {
        "id": 13,
        "name": "Kinkaku-ji",
        "description": "Golden Pavilion, a Zen temple in Kyoto, Japan",
        "category": "religious",
        "location": {"city": "Kyoto", "country": "Japan", "region": "Kansai", "continent": "Asia"},
        "rating": 4.5,
        "image_url": "https://example.com/kinkaku-ji.jpg",
        "website": "https://www.shokoku-ji.jp",
        "opening_hours": "9:00 AM - 5:00 PM",
        "entry_fee": "¥500",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-20",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Low",
        "time_needed": "1-2 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Spiritual",
        "recommended_packing_list": ["Camera", "Guidebook"]
    },
    {
        "id": 14,
        "name": "Sydney Opera House",
        "description": "Multi-venue performing arts center in Sydney, Australia",
        "category": "modern",
        "location": {"city": "Sydney", "country": "Australia", "region": "New South Wales", "continent": "Oceania"},
        "rating": 4.4,
        "image_url": "https://example.com/sydney-opera.jpg",
        "website": "https://www.sydneyoperahouse.com",
        "opening_hours": "9:00 AM - 8:30 PM",
        "entry_fee": "$43 - $175",
        "disability_accessible": True,
        "outdoors": False,
        "group_size": "1-100+",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Camera", "Guidebook"]
    },
    {
        "id": 15,
        "name": "Christ the Redeemer",
        "description": "Art Deco statue of Jesus Christ in Rio de Janeiro, Brazil",
        "category": "religious",
        "location": {"city": "Rio de Janeiro", "country": "Brazil", "region": "Rio de Janeiro", "continent": "South America"},
        "rating": 4.5,
        "image_url": "https://example.com/christ-redeemer.jpg",
        "website": "https://www.cristoredentor.com.br",
        "opening_hours": "8:00 AM - 7:00 PM",
        "entry_fee": "R$65 - R$98",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-40",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Spiritual",
        "recommended_packing_list": ["Camera", "Water bottle"]
    },
    # Additional mock attractions with new fields
    {
        "id": 16,
        "name": "Berlin Zoo",
        "description": "One of the world's most famous zoos, home to a wide variety of animals.",
        "category": "parks",
        "location": {"city": "Berlin", "country": "Germany", "region": "Berlin", "continent": "Europe"},
        "rating": 4.2,
        "image_url": "https://example.com/berlin-zoo.jpg",
        "website": "https://www.zoo-berlin.de",
        "opening_hours": "9:00 AM - 6:30 PM",
        "entry_fee": "€16 - €21",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-4 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Family",
        "recommended_packing_list": ["Camera", "Snacks", "Water bottle"]
    },
    {
        "id": 17,
        "name": "Mount Fuji Hike",
        "description": "Climb Japan's iconic mountain for breathtaking views.",
        "category": "mountains",
        "location": {"city": "Fujinomiya", "country": "Japan", "region": "Shizuoka", "continent": "Asia"},
        "rating": 4.9,
        "image_url": "https://example.com/mount-fuji.jpg",
        "website": "https://www.japan-guide.com/e/e6901.html",
        "opening_hours": "July - September",
        "entry_fee": "¥1000",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-10",
        "age_recommendation": "12+",
        "age_restriction": "12+ only",
        "budget": "Low",
        "time_needed": "Full day",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Hiking boots", "Jacket", "Snacks", "Water bottle"]
    },
    {
        "id": 18,
        "name": "Venice Gondola Ride",
        "description": "Experience the romantic canals of Venice on a traditional gondola.",
        "category": "entertainment",
        "location": {"city": "Venice", "country": "Italy", "region": "Veneto", "continent": "Europe"},
        "rating": 4.7,
        "image_url": "https://example.com/venice-gondola.jpg",
        "website": "https://www.venicegondola.com",
        "opening_hours": "9:00 AM - 8:00 PM",
        "entry_fee": "€80 - €120",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-6",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "30-60 min",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Romantic",
        "recommended_packing_list": ["Camera", "Sunglasses"]
    },
    {
        "id": 19,
        "name": "London Science Museum",
        "description": "Interactive science exhibits for all ages.",
        "category": "museums",
        "location": {"city": "London", "country": "UK", "region": "England", "continent": "Europe"},
        "rating": 4.5,
        "image_url": "https://example.com/london-science-museum.jpg",
        "website": "https://www.sciencemuseum.org.uk",
        "opening_hours": "10:00 AM - 6:00 PM",
        "entry_fee": "Free",
        "disability_accessible": True,
        "outdoors": False,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Free",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Educational",
        "recommended_packing_list": ["Notebook", "Camera"]
    },
    {
        "id": 20,
        "name": "Bondi Beach",
        "description": "Famous beach in Sydney, popular for surfing and sunbathing.",
        "category": "beaches",
        "location": {"city": "Sydney", "country": "Australia", "region": "New South Wales", "continent": "Oceania"},
        "rating": 4.8,
        "image_url": "https://example.com/bondi-beach.jpg",
        "website": "https://www.bondivillage.com",
        "opening_hours": "24/7",
        "entry_fee": "Free",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-100+",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Free",
        "time_needed": "2-6 hours",
        "pet_friendly": True,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Relaxing",
        "recommended_packing_list": ["Swimsuit", "Towel", "Sunscreen", "Surfboard"]
    },
    {
        "id": 21,
        "name": "Angkor Thom",
        "description": "Last capital city of the Khmer Empire, featuring the iconic Bayon Temple with stone faces.",
        "category": "historical",
        "location": {"city": "Siem Reap", "country": "Cambodia", "region": "Siem Reap", "continent": "Asia"},
        "rating": 4.7,
        "image_url": "https://example.com/angkor-thom.jpg",
        "website": "https://www.angkor.org",
        "opening_hours": "5:00 AM - 6:00 PM",
        "entry_fee": "$37 (1 day), $62 (3 days)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-25",
        "age_recommendation": "8+",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "3-4 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Spiritual",
        "recommended_packing_list": ["Hat", "Water bottle", "Camera", "Comfortable shoes"]
    },
    {
        "id": 22,
        "name": "Forbidden City",
        "description": "Imperial palace complex from the Ming dynasty, now a UNESCO World Heritage Site.",
        "category": "historical",
        "location": {"city": "Beijing", "country": "China", "region": "Beijing", "continent": "Asia"},
        "rating": 4.6,
        "image_url": "https://example.com/forbidden-city.jpg",
        "website": "https://www.dpm.org.cn",
        "opening_hours": "8:30 AM - 5:00 PM",
        "entry_fee": "¥60 - ¥80",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-40",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Low",
        "time_needed": "3-5 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Camera", "Guidebook", "Water bottle", "Comfortable shoes"]
    },
    {
        "id": 23,
        "name": "Borobudur Temple",
        "description": "9th-century Mahayana Buddhist temple and UNESCO World Heritage Site with stunning sunrise views.",
        "category": "religious",
        "location": {"city": "Yogyakarta", "country": "Indonesia", "region": "Central Java", "continent": "Asia"},
        "rating": 4.8,
        "image_url": "https://example.com/borobudur.jpg",
        "website": "https://borobudurpark.com",
        "opening_hours": "6:00 AM - 5:00 PM",
        "entry_fee": "475,000 IDR (foreigners), 50,000 IDR (locals)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "8+",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Spiritual",
        "recommended_packing_list": ["Hat", "Sunscreen", "Camera", "Water bottle"]
    },
    {
        "id": 24,
        "name": "Phi Phi Islands",
        "description": "Tropical paradise with crystal clear waters, perfect for snorkeling and diving.",
        "category": "beaches",
        "location": {"city": "Krabi", "country": "Thailand", "region": "Krabi", "continent": "Asia"},
        "rating": 4.5,
        "image_url": "https://example.com/phi-phi.jpg",
        "website": "https://www.phiphi.com",
        "opening_hours": "24/7",
        "entry_fee": "Free (boat tour costs extra)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-20",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "Full day",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Relaxing",
        "recommended_packing_list": ["Swimsuit", "Snorkel gear", "Sunscreen", "Water shoes", "Camera"]
    },
    {
        "id": 25,
        "name": "Marina Bay Sands SkyPark",
        "description": "Iconic infinity pool and observation deck offering panoramic views of Singapore skyline.",
        "category": "modern",
        "location": {"city": "Singapore", "country": "Singapore", "region": "Central Singapore", "continent": "Asia"},
        "rating": 4.4,
        "image_url": "https://example.com/marina-bay-sands.jpg",
        "website": "https://www.marinabaysands.com",
        "opening_hours": "9:30 AM - 10:00 PM",
        "entry_fee": "S$26 (observation deck), pool for hotel guests only",
        "disability_accessible": True,
        "outdoors": False,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "1-2 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Luxurious",
        "recommended_packing_list": ["Camera", "Sunglasses", "Light jacket"]
    },
    {
        "id": 26,
        "name": "Pyramids of Giza",
        "description": "Ancient Egyptian pyramids and the Great Sphinx, one of the Seven Wonders of the Ancient World.",
        "category": "historical",
        "location": {"city": "Giza", "country": "Egypt", "region": "Cairo Governorate", "continent": "Africa"},
        "rating": 4.8,
        "image_url": "https://example.com/pyramids-giza.jpg",
        "website": "https://www.egypt.travel",
        "opening_hours": "8:00 AM - 5:00 PM",
        "entry_fee": "400 EGP (foreigners), 80 EGP (locals)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "3-4 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Hat", "Sunscreen", "Water bottle", "Camera", "Comfortable shoes"]
    },
    {
        "id": 27,
        "name": "Serengeti National Park",
        "description": "World-famous wildlife reserve known for the Great Migration and diverse African wildlife.",
        "category": "natural",
        "location": {"city": "Arusha", "country": "Tanzania", "region": "Mara Region", "continent": "Africa"},
        "rating": 4.9,
        "image_url": "https://example.com/serengeti.jpg",
        "website": "https://www.tanzaniaparks.go.tz",
        "opening_hours": "6:00 AM - 6:00 PM",
        "entry_fee": "$71 per day (foreigners), 10,000 TSH (locals)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-15",
        "age_recommendation": "8+",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "Full day",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Binoculars", "Camera with zoom lens", "Hat", "Safari clothes", "Sunscreen"]
    },
    {
        "id": 28,
        "name": "Table Mountain",
        "description": "Flat-topped mountain offering spectacular views of Cape Town and surrounding areas.",
        "category": "mountains",
        "location": {"city": "Cape Town", "country": "South Africa", "region": "Western Cape", "continent": "Africa"},
        "rating": 4.7,
        "image_url": "https://example.com/table-mountain.jpg",
        "website": "https://www.tablemountain.net",
        "opening_hours": "8:00 AM - 6:00 PM",
        "entry_fee": "R395 (cable car), Free (hiking)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-4 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Camera", "Jacket", "Comfortable shoes", "Water bottle"]
    },
    {
        "id": 29,
        "name": "Victoria Falls",
        "description": "One of the world's largest waterfalls, known locally as 'Mosi-oa-Tunya' (The Smoke That Thunders).",
        "category": "natural",
        "location": {"city": "Livingstone", "country": "Zambia", "region": "Southern Province", "continent": "Africa"},
        "rating": 4.8,
        "image_url": "https://example.com/victoria-falls.jpg",
        "website": "https://www.victoriafalls-guide.net",
        "opening_hours": "6:00 AM - 6:00 PM",
        "entry_fee": "$30 (foreigners), ZMW 40 (locals)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-40",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Raincoat", "Camera", "Water bottle", "Non-slip shoes"]
    },
    {
        "id": 30,
        "name": "Stone Town",
        "description": "Historic quarter of Zanzibar City with unique blend of Arab, Persian, Indian, and European architecture.",
        "category": "cultural",
        "location": {"city": "Zanzibar", "country": "Tanzania", "region": "Zanzibar", "continent": "Africa"},
        "rating": 4.5,
        "image_url": "https://example.com/stone-town.jpg",
        "website": "https://www.zanzibartourism.net",
        "opening_hours": "24/7",
        "entry_fee": "Free",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-25",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Low",
        "time_needed": "3-5 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Camera", "Comfortable walking shoes", "Hat", "Water bottle"]
    },
    {
        "id": 31,
        "name": "Grand Canyon",
        "description": "Massive canyon carved by the Colorado River, offering breathtaking views and hiking trails.",
        "category": "natural",
        "location": {"city": "Grand Canyon", "country": "USA", "region": "Arizona", "continent": "North America"},
        "rating": 4.8,
        "image_url": "https://example.com/grand-canyon.jpg",
        "website": "https://www.nps.gov/grca",
        "opening_hours": "24/7 (visitor centers vary)",
        "entry_fee": "$35 per vehicle (7 days)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-8 hours",
        "pet_friendly": True,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Camera", "Water bottle", "Hat", "Hiking boots", "Sunscreen"]
    },
    {
        "id": 32,
        "name": "Chichen Itza",
        "description": "Pre-Columbian Maya city with the famous El Castillo pyramid, UNESCO World Heritage Site.",
        "category": "historical",
        "location": {"city": "Yucatan", "country": "Mexico", "region": "Yucatan", "continent": "North America"},
        "rating": 4.6,
        "image_url": "https://example.com/chichen-itza.jpg",
        "website": "https://www.chichenitza.com",
        "opening_hours": "8:00 AM - 5:00 PM",
        "entry_fee": "$533 MXN (foreigners), $230 MXN (locals)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-40",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Hat", "Sunscreen", "Camera", "Water bottle", "Comfortable shoes"]
    },
    {
        "id": 33,
        "name": "Iguazu Falls",
        "description": "Spectacular waterfalls on the border of Argentina and Brazil, one of the New Seven Wonders of Nature.",
        "category": "natural",
        "location": {"city": "Puerto Iguazu", "country": "Argentina", "region": "Misiones", "continent": "South America"},
        "rating": 4.9,
        "image_url": "https://example.com/iguazu-falls.jpg",
        "website": "https://www.iguazuargentina.com",
        "opening_hours": "8:00 AM - 6:00 PM",
        "entry_fee": "$30 USD (foreigners), $800 ARS (locals)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "4-6 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Raincoat", "Camera", "Water bottle", "Non-slip shoes", "Sunscreen"]
    },
    {
        "id": 34,
        "name": "Banff National Park",
        "description": "Canada's oldest national park featuring stunning mountain scenery, lakes, and wildlife.",
        "category": "natural",
        "location": {"city": "Banff", "country": "Canada", "region": "Alberta", "continent": "North America"},
        "rating": 4.7,
        "image_url": "https://example.com/banff.jpg",
        "website": "https://www.pc.gc.ca/en/pn-np/ab/banff",
        "opening_hours": "24/7",
        "entry_fee": "$10.50 CAD per day",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "Full day",
        "pet_friendly": True,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Relaxing",
        "recommended_packing_list": ["Warm jacket", "Hiking boots", "Camera", "Water bottle", "Bear spray"]
    },
    {
        "id": 35,
        "name": "Easter Island Moai",
        "description": "Mysterious ancient stone statues scattered across remote Polynesian island.",
        "category": "historical",
        "location": {"city": "Hanga Roa", "country": "Chile", "region": "Valparaiso", "continent": "South America"},
        "rating": 4.5,
        "image_url": "https://example.com/easter-island.jpg",
        "website": "https://www.rapanui.co.cl",
        "opening_hours": "9:00 AM - 6:00 PM",
        "entry_fee": "$80 USD (foreigners), $20 USD (locals)",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-20",
        "age_recommendation": "10+",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "3-5 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Mysterious",
        "recommended_packing_list": ["Hat", "Sunscreen", "Camera", "Water bottle", "Comfortable walking shoes"]
    },
    {
        "id": 36,
        "name": "Neuschwanstein Castle",
        "description": "Fairy-tale castle in the Bavarian Alps that inspired Disney's Sleeping Beauty Castle.",
        "category": "architecture",
        "location": {"city": "Fussen", "country": "Germany", "region": "Bavaria", "continent": "Europe"},
        "rating": 4.5,
        "image_url": "https://example.com/neuschwanstein.jpg",
        "website": "https://www.neuschwanstein.de",
        "opening_hours": "9:00 AM - 6:00 PM",
        "entry_fee": "€15 (adults), €13 (students)",
        "disability_accessible": False,
        "outdoors": False,
        "group_size": "1-35",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-3 hours",
        "pet_friendly": False,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Romantic",
        "recommended_packing_list": ["Camera", "Comfortable walking shoes", "Light jacket"]
    },
    {
        "id": 37,
        "name": "Northern Lights in Iceland",
        "description": "Natural light display in polar regions, best viewed from Iceland's dark winter skies.",
        "category": "natural",
        "location": {"city": "Reykjavik", "country": "Iceland", "region": "Capital Region", "continent": "Europe"},
        "rating": 4.9,
        "image_url": "https://example.com/northern-lights.jpg",
        "website": "https://www.northernlightsiceland.com",
        "opening_hours": "September - March (weather dependent)",
        "entry_fee": "Free (tour costs extra)",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-50",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "2-4 hours",
        "pet_friendly": True,
        "wifi_available": False,
        "photogenic": True,
        "mood": "Magical",
        "recommended_packing_list": ["Warm winter clothes", "Camera with tripod", "Hot drinks", "Blanket"]
    },
    {
        "id": 38,
        "name": "Swiss Alps Jungfraujoch",
        "description": "Top of Europe with glaciers, snow activities, and panoramic mountain views.",
        "category": "mountains",
        "location": {"city": "Interlaken", "country": "Switzerland", "region": "Bern", "continent": "Europe"},
        "rating": 4.6,
        "image_url": "https://example.com/jungfraujoch.jpg",
        "website": "https://www.jungfraujoch.ch",
        "opening_hours": "8:00 AM - 5:00 PM",
        "entry_fee": "CHF 75 - CHF 150",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-40",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "High",
        "time_needed": "6-8 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Adventurous",
        "recommended_packing_list": ["Warm jacket", "Sunglasses", "Camera", "Sunscreen", "Gloves"]
    },
    {
        "id": 39,
        "name": "Prague Castle",
        "description": "Ancient castle complex and UNESCO World Heritage Site overlooking the city of Prague.",
        "category": "historical",
        "location": {"city": "Prague", "country": "Czech Republic", "region": "Prague", "continent": "Europe"},
        "rating": 4.4,
        "image_url": "https://example.com/prague-castle.jpg",
        "website": "https://www.hrad.cz",
        "opening_hours": "9:00 AM - 5:00 PM",
        "entry_fee": "350 CZK - 570 CZK",
        "disability_accessible": True,
        "outdoors": True,
        "group_size": "1-30",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "3-4 hours",
        "pet_friendly": False,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Cultural",
        "recommended_packing_list": ["Camera", "Comfortable shoes", "Guidebook", "Light jacket"]
    },
    {
        "id": 40,
        "name": "Amalfi Coast",
        "description": "Stunning coastal drive with picturesque towns, dramatic cliffs, and Mediterranean views.",
        "category": "natural",
        "location": {"city": "Amalfi", "country": "Italy", "region": "Campania", "continent": "Europe"},
        "rating": 4.7,
        "image_url": "https://example.com/amalfi-coast.jpg",
        "website": "https://www.amalficoast.it",
        "opening_hours": "24/7",
        "entry_fee": "Free",
        "disability_accessible": False,
        "outdoors": True,
        "group_size": "1-25",
        "age_recommendation": "All ages",
        "age_restriction": None,
        "budget": "Medium",
        "time_needed": "Full day",
        "pet_friendly": True,
        "wifi_available": True,
        "photogenic": True,
        "mood": "Romantic",
        "recommended_packing_list": ["Camera", "Sunscreen", "Comfortable shoes", "Swimsuit", "Hat"]
    }
]

# World wonders mock data
WORLD_WONDERS = [1, 2, 3, 4, 6, 8, 10, 15]  # IDs from MOCK_ATTRACTIONS that are world wonders