[project]
name = "cinema-mcp"
version = "1.0.0"
description = "MCP server for discovering and booking movie showings"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.13.1",
]